# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cticket.proto\x12\x06ticket\"\\\n\rTicketRequest\x12\x0f\n\x07\x66romTRQ\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x1a\n\x04user\x18\x03 \x01(\x0b\x32\x0c.ticket.User\x12\x12\n\nprice_paid\x18\x04 \x01(\x02\"+\n\x15ReceiptDetailsRequest\x12\x12\n\nreceipt_id\x18\x01 \x01(\t\"!\n\x0eSectionRequest\x12\x0f\n\x07section\x18\x01 \x01(\t\"\"\n\x11RemoveUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"4\n\x11ModifySeatRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08new_seat\x18\x02 \x01(\t\"P\n\x04User\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nprice_paid\x18\x04 \x01(\x02\"~\n\rTicketReceipt\x12\x12\n\nreceipt_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66romTRP\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\x1a\n\x04user\x18\x04 \x01(\x0b\x32\x0c.ticket.User\x12\x12\n\nprice_paid\x18\x05 \x01(\x02\x12\x0c\n\x04seat\x18\x06 \x01(\t\"=\n\x16UsersBySectionResponse\x12#\n\tuser_seat\x18\x01 \x03(\x0b\x32\x10.ticket.UserSeat\")\n\x08UserSeat\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04seat\x18\x02 \x01(\t\"%\n\x12RemoveUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x12ModifySeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf5\x02\n\x0cTrainService\x12>\n\x0ePurchaseTicket\x12\x15.ticket.TicketRequest\x1a\x15.ticket.TicketReceipt\x12I\n\x11GetReceiptDetails\x12\x1d.ticket.ReceiptDetailsRequest\x1a\x15.ticket.TicketReceipt\x12L\n\x12ViewUsersBySection\x12\x16.ticket.SectionRequest\x1a\x1e.ticket.UsersBySectionResponse\x12\x43\n\nRemoveUser\x12\x19.ticket.RemoveUserRequest\x1a\x1a.ticket.RemoveUserResponse\x12G\n\x0eModifyUserSeat\x12\x19.ticket.ModifySeatRequest\x1a\x1a.ticket.ModifySeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TICKETREQUEST']._serialized_start=24
  _globals['_TICKETREQUEST']._serialized_end=116
  _globals['_RECEIPTDETAILSREQUEST']._serialized_start=118
  _globals['_RECEIPTDETAILSREQUEST']._serialized_end=161
  _globals['_SECTIONREQUEST']._serialized_start=163
  _globals['_SECTIONREQUEST']._serialized_end=196
  _globals['_REMOVEUSERREQUEST']._serialized_start=198
  _globals['_REMOVEUSERREQUEST']._serialized_end=232
  _globals['_MODIFYSEATREQUEST']._serialized_start=234
  _globals['_MODIFYSEATREQUEST']._serialized_end=286
  _globals['_USER']._serialized_start=288
  _globals['_USER']._serialized_end=368
  _globals['_TICKETRECEIPT']._serialized_start=370
  _globals['_TICKETRECEIPT']._serialized_end=496
  _globals['_USERSBYSECTIONRESPONSE']._serialized_start=498
  _globals['_USERSBYSECTIONRESPONSE']._serialized_end=559
  _globals['_USERSEAT']._serialized_start=561
  _globals['_USERSEAT']._serialized_end=602
  _globals['_REMOVEUSERRESPONSE']._serialized_start=604
  _globals['_REMOVEUSERRESPONSE']._serialized_end=641
  _globals['_MODIFYSEATRESPONSE']._serialized_start=643
  _globals['_MODIFYSEATRESPONSE']._serialized_end=680
  _globals['_TRAINSERVICE']._serialized_start=683
  _globals['_TRAINSERVICE']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
